### PR TITLE
Update dependencies for Scala 2.12

### PR DESCRIPTION
**Pull request by Leonti**
Hi!
Could you merge it and publish a new version for Scala 2.12.1?
Cheers,
Leonti

### CODE REVIEW

**Comment by choffmeister** [comment]
Hi @Leonti. Sorry for the delay. Did not see the notification. Actually it is already released for 2.12 with version `0.3.1`

**Comment by choffmeister** [comment]
But actually I really don't know currently, where the according branch is... Weired

**Comment by choffmeister** [comment]
@Leonti Will close this in favor of #5 where I used your commit as base for adding cross build and doing some other cleanup. Will merge and release it soon. Thanks!

**Comment by Leonti** [comment]
Awesome, thanks!

**Pull request closed without merging**
